#########################################################
# You must re-run configure.py after changing this file #
#########################################################

# extab, extabindex and ctor sections should be disabled(if a file has a ctor section then just don't compile it)
# these should work but just don't, results in linker errors

#libs/RVL_SDK/src/revolution/os/__start.c:
  #.init: [0x80004000, 0x80004360]
  #.sbss: [0x8050dc80, 0x8050dc88]

#libs/RVL_SDK/src/revolution/os/__ppc_eabi_init.cpp:
  #.init: [0x80004360, 0x800043c4]
  #.text: [0x802942f0, 0x802943b0]

libs/RVL_SDK/src/revolution/BASE/PPCArch.c:
  .text: [0x802869b0, 0x80286bc0]
  .data: [0x804d0f18, 0x804d0f50]

#libs/RVL_SDK/src/revolution/ARC/arc.c:
  #.text: [0x802d9ce0, 0x802da6b8]
  #.data: [0x804e8718, 0x804e8788]
  #.sdata: [0x8050d198, 0x8050d1a0]

libs/RVL_SDK/src/revolution/AI/ai.c:
  .text: [0x802a4ad0, 0x802a507c]
  .data: [0x804e1688, 0x804e16d0]
  .sdata: [0x8050cf08, 0x8050cf10]
  .sbss: [0x8050dec0, 0x8050df00]

#libs/RVL_SDK/src/revolution/AX/AX.c:

libs/RVL_SDK/src/revolution/DSP/dsp.c:
  .text: [0x802a9360, 0x802a95bc]
  .data: [0x804e4920, 0x804e49a0]
  .sdata: [0x8050cf28, 0x8050cf30]
  .sbss: [0x8050e040, 0x8050e048]

libs/RVL_SDK/src/revolution/DSP/dsp_debug.c:
  .text: [0x802a95c0, 0x802a9610]

libs/RVL_SDK/src/revolution/DSP/dsp_task.c:
  .text: [0x802a9610, 0x802a9ea8]
  .data: [0x804e49a0, 0x804e4ae0]
  .sbss: [0x8050e048, 0x8050e060]
  
#libs/PowerPC_EABI_Support/Runtime/global_destructor_chain.c:
  #.text: [0x802b1f14, 0x802b1f74]
  #.sbss: [0x8050e0c0, 0x8050e0c8]

#libs/PowerPC_EABI_Support/Runtime/NMWException.cp:
  #.text: [0x802b1f74, 0x802b24f4]
  #.sdata: [0x8050cf98, 0x8050cfa0]
  #extab: [0x8001196c, 0x800119ac]
  #extabindex: [0x8001fdb8, 0x8001fde8]

#libs/PowerPC_EABI_Support/Runtime/__init_cpp_exceptions.cpp:
  #.text: [0x802b2c60, 0x802b2cd0]
  #.sdata: [0x8050cfa0, 0x8050cfa8]
  #.ctors: [0x80480080, 0x80480084]
  #.dtors: [0x80480160, 0x80480168]

#libs/PowerPC_EABI_Support/src/MSL/MSL_C/MSL_Common/buffer_io.c:
  #.text: [0x802b73ec, 0x802b76f8]

#libs/PowerPC_EABI_Support/src/MSL/MSL_C/MSL_Common/direct_io.c:
  #.text: [0x802b76f8, 0x802b7d48]

#libs/PowerPC_EABI_Support/src/MSL/MSL_C/MSL_Common/file_io.c:
  #.text: [0x802b7d48, 0x802b82b8]

libs/PowerPC_EABI_Support/src/MSL/MSL_C/MSL_Common/FILE_POS.c:
  .text: [0x802b82b8, 0x802b8574]

libs/PowerPC_EABI_Support/src/MSL/MSL_C/MSL_Common/mbstring.c:
  .text: [0x802b8574, 0x802b876c]

libs/PowerPC_EABI_Support/src/MSL/MSL_C/MSL_Common/mem.c:
  .text: [0x802b876c, 0x802b88dc]

libs/PowerPC_EABI_Support/src/MSL/MSL_C/MSL_Common/mem_funcs.c:
  .text: [0x802b88dc, 0x802b8bac]

libs/PowerPC_EABI_Support/src/MSL/MSL_C/MSL_Common/math_api.c:
  .text: [0x802b8bac, 0x802b8ca0]

libs/PowerPC_EABI_Support/src/MSL/MSL_C/MSL_Common/misc_io.c:
  .text: [0x802b8ca0, 0x802b8cc0]

libs/PowerPC_EABI_Support/src/MSL/MSL_C/MSL_Common/printf.c:
  .text: [0x802b8cc0, 0x802bb184]
  .rodata: [0x804ac048, 0x804ac070]
  .data: [0x804e59e8, 0x804e5c18]
  .sdata: [0x8050cfb0, 0x8050cfb8]
  .sdata2: [0x80511678, 0x80511680]

#libs/PowerPC_EABI_Support/src/MSL/MSL_C/MSL_Common/qsort.c:
  #.text: [0x802bb184, 0x0x802bb2f4]

libs/PowerPC_EABI_Support/src/MSL/MSL_C/MSL_Common/rand.c:
  .text: [0x802bb2f4, 0x802bb31c]
  .sdata: [0x8050cfb8, 0x8050cfc0]

libs/PowerPC_EABI_Support/src/MSL/MSL_C/MSL_Common/scanf.c:
  .text: [0x802bb31c, 0x802bc800]
  .rodata: [0x804ac070, 0x804ac098]
  .data: [0x804e5c18, 0x804e5e88]

libs/PowerPC_EABI_Support/src/MSL/MSL_C/MSL_Common/signal.c:
  .text: [0x802bc800, 0x802bc8a8]
  .bss: [0x808b4aa0, 0x808b4ac0]

#libs/PowerPC_EABI_Support/src/MSL/MSL_C/MSL_Common/string.c:
  #.text: [0x802bc8a8, 0x802bcde4]
  #.sdata: [0x8050cfc0, 0x8050cfc8]

libs/PowerPC_EABI_Support/src/MSL/MSL_C/MSL_Common/strtold.c:
  .text: [0x802bcde4, 0x802be164]
  .rodata: [0x804ac098, 0x804ac0a8]
  .sdata2: [0x80511688, 0x805116a8]

libs/PowerPC_EABI_Support/src/MSL/MSL_C/MSL_Common/strtoul.c:
  .text: [0x802be164, 0x802bec78]

libs/PowerPC_EABI_Support/src/MSL/MSL_C/MSL_Common/wmem.c:
  .text: [0x802bec78, 0x802beca8]  

libs/PowerPC_EABI_Support/src/MSL/MSL_C/MSL_Common/wprintf.c:
  .text: [0x802beca8, 0x802c0ec8]
  .rodata: [0x804ac6a8, 0x804ac6b0]
  .data: [0x804e5e88, 0x804e6128]
  .sdata2: [0x805116a8, 0x805116b0]

libs/PowerPC_EABI_Support/src/MSL/MSL_C/MSL_Common/wstring.c:
  .text: [0x802c0ec8, 0x802c0fa4]

libs/PowerPC_EABI_Support/src/MSL/MSL_C/MSL_Common/wchar_io.c:
  .text: [0x802c0fa4, 0x802c101c]

libs/PowerPC_EABI_Support/src/MSL/MSL_C/MSL_Common/extras.c:
  .text: [0x802c5350, 0x802c5494]

libs/RVL_SDK/src/revolution/EXI/EXIBios.c:
  .text: [0x802c54a0, 0x802c6d98]
  .data: [0x804e6128, 0x804e6170]
  .sdata: [0x8050cfd8, 0x8050cfe0]
  .sbss: [0x8050e100, 0x8050e108]
  .bss: [0x808b4ac0, 0x808b4b80]

libs/RVL_SDK/src/revolution/EXI/EXICommon.c:
  .text: [0x802c70e0, 0x802c7268]
  .sdata2: [0x80511bc0, 0x80511bc8]

libs/RVL_SDK/src/revolution/MEM/mem_heapCommon.c:
  .text: [0x802ce760, 0x802cebcc]
  .sbss: [0x8050e198, 0x8050e1a0]
  .bss: [0x808b7260, 0x808b7288]

libs/RVL_SDK/src/revolution/MEM/mem_allocator.c:
  .text: [0x802cf950, 0x802cf9ac]
  .sdata2: [0x80511bd0, 0x80511bd8]

libs/RVL_SDK/src/revolution/MEM/mem_list.c:
  .text: [0x802cf9b0, 0x802cfad0]

libs/RVL_SDK/src/revolution/SC/scapi.c:
  .text: [0x802d91d0, 0x802d96d0]
  .data: [0x804e8688, 0x804e86b8]

libs/RVL_SDK/src/revolution/SC/scapi_prdinfo.c:
  .text: [0x802d96d0, 0x802d9a04]
  .data: [0x804e86b8, 0x804e8718]
  .sdata: [0x8050d170, 0x8050d198]
  .sbss: [0x8050e230, 0x8050e238]

#libs/RVL_SDK/src/revolution/USB/usb.c:
  #.text: [0x80320920, 0x80321830]
  #.data: [0x804ef910, 0x804f0140]
  #.sdata: [0x8050d278, 0x8050d288]

src/Shade/std/shd_stdarg.cpp:
  .text: [0x803346e0, 0x8033496c]
  #extab: [0x800120a4, 0x800120b4]
  #extabindex: [0x8002037c, 0x80020394] 
  
libs/nw4r/db/db_console.cpp:
  .text: [0x80392fb0, 0x8039308c]

libs/nw4r/snd/snd_adpcm.cpp:
  .text: [0x8040e7e0, 0x8040e86c]